from __future__ import annotations

import asyncio
import logging
import os
import re
from dataclasses import dataclass, field
from datetime import datetime
import json
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional

from openai.types.responses import ResponseContentPartDoneEvent, ResponseTextDeltaEvent

from agents import Agent, Runner
from agents import SQLiteSession

from .ingestion import build_ingestion_agent
from .note import build_note_agent
from .qa import build_qa_agent
from .quiz_agent import build_quiz_agent
from .routing import (
    RoutingDecision,
    apply_deterministic_routing,
    extract_source_mentions,
    should_use_source_filter,
)
from .web import build_web_agent

from ai_tutor.config.schema import RetrievalConfig
from ai_tutor.data_models import RetrievalHit
from ai_tutor.ingestion.embeddings import EmbeddingClient
from ai_tutor.learning.models import LearnerProfile
from ai_tutor.learning.quiz import Quiz, QuizEvaluation, QuizService
from ai_tutor.retrieval.retriever import Retriever
from ai_tutor.retrieval.vector_store import VectorStore
# SearchTool removed - web_agent uses WebSearchTool directly

logger = logging.getLogger(__name__)


@dataclass
class TutorResponse:
    """
    Structured response container for tutor interactions.
    
    This dataclass encapsulates all information returned from a tutoring session,
    including the generated answer, retrieval evidence, personalization hints,
    and optional quiz payloads.
    
    Attributes
    ----------
    answer : str
        The generated response text from the tutor agent. May include citation
        markers like [1], [2] that correspond to the citations list.
    hits : List[RetrievalHit]
        Raw retrieval results from the vector store, containing chunks and similarity
        scores. Empty for web-sourced or quiz-only responses.
    citations : List[str]
        Formatted citation strings (e.g., "[1] Title (Doc: id, Page: 42)") that
        map to bracketed indices in the answer text. Empty if no local sources used.
    style : str
        The explanation style used for this response. One of "scaffolded" (detailed,
        step-by-step), "stepwise" (moderate guidance), or "concise" (advanced).
    next_topic : Optional[str]
        Suggested next topic for the learner based on their current progress and
        knowledge gaps. None if not applicable.
    difficulty : Optional[str]
        Current difficulty level label for the learner in this domain. One of
        "foundational guidance", "guided practice", or "independent challenge".
    source : Optional[str]
        Origin of the answer. One of "local" (RAG from course materials), "web"
        (internet search), "quiz" (assessment generation), or None.
    quiz : Optional[Quiz]
        Generated quiz object if the interaction produced an assessment. Contains
        questions, correct answers, and explanations.
    """

    answer: str
    hits: List[RetrievalHit]
    citations: List[str]
    style: str
    next_topic: Optional[str] = None
    difficulty: Optional[str] = None
    source: Optional[str] = None
    quiz: Optional[Quiz] = None


@dataclass
class AgentState:
    """
    Shared state object for multi-agent communication.
    
    This mutable state container allows specialist agents (QA, Web, Quiz) to
    store their results, which the orchestrator then collects and formats into
    a unified TutorResponse. The state is reset at the start of each new query.
    
    Attributes
    ----------
    last_hits : List[RetrievalHit]
        Retrieval results from the most recent vector search. Used by QA agent
        to pass evidence back to orchestrator.
    last_citations : List[str]
        Formatted citation strings generated by specialist agents. Collected
        and attached to the final response.
    last_source : Optional[str]
        Identifier for the agent that handled the last query ("local", "web", etc.).
        Helps orchestrator determine response formatting.
    last_quiz : Optional[Quiz]
        Quiz object generated by the quiz tool. If present, the response includes
        interactive assessment UI.
    """
    
    last_hits: List[RetrievalHit] = field(default_factory=list)
    last_citations: List[str] = field(default_factory=list)
    last_source: Optional[str] = None
    last_quiz: Optional[Quiz] = None

    def reset(self) -> None:
        """
        Clear all state variables to prepare for a new query.
        
        Called at the start of each answer() invocation to ensure agents don't
        carry over results from previous interactions.
        """
        self.last_hits.clear()
        self.last_citations.clear()
        self.last_source = None
        self.last_quiz = None


class TutorAgent:
    """
    Multi-agent tutoring coordinator using the OpenAI Agents SDK.
    
    This class implements an agent-first architecture with a thin router that
    applies deterministic rules (document references, quizzes, ingestion, news)
    before delegating to specialist agents. When heuristics are inconclusive,
    a lightweight routing agent produces structured JSON to guide delegation.
    
    Supported capabilities:
    - STEM Q&A with retrieval-augmented generation (qa_agent)
    - Current events and web searches (web_agent)
    - Document ingestion and corpus management (ingestion_agent)
    - Summaries and note files (note_agent)
    - Quiz generation/evaluation (quiz_agent + QuizService)
    
    Conversation context is maintained via SQLite sessions that rotate
    automatically to prevent prompt bloat. Specialist results are stored in
    AgentState and formatted into TutorResponse objects.
    
    Attributes
    ----------
    MIN_CONFIDENCE : float
        Minimum similarity score (0.2) for retrieval results to be considered
        relevant. Queries with no hits above this threshold fall back to web search.
    retriever : Retriever
        Vector search coordinator that embeds queries and retrieves similar chunks.
    # Web search is handled directly by web_agent using WebSearchTool
    ingest_fn : Callable
        Directory ingestion function for processing and indexing new documents.
    sessions : Dict[str, SQLiteSession]
        In-memory cache of active conversation sessions, keyed by learner_id.
    state : AgentState
        Shared mutable state for inter-agent communication.
    session_db_path : Path
        SQLite database path for persistent conversation history.
    quiz_service : QuizService
        Assessment generator that creates and evaluates quizzes.
    """

    MIN_CONFIDENCE = 0.2  # Minimum retrieval score for accepting local results

    def __init__(
        self,
        retrieval_config: RetrievalConfig,
        embedder: EmbeddingClient,
        vector_store: VectorStore,
        ingest_directory: Callable[[Path], object],
        session_db_path: Path,
        quiz_service: QuizService,
        mcp_servers: Optional[Dict[str, Any]] = None,
    ):
        """
        Initialize the multi-agent system with all required dependencies.
        
        Parameters
        ----------
        retrieval_config : RetrievalConfig
            Configuration for vector search (top_k, thresholds, etc.).
        embedder : EmbeddingClient
            Sentence transformer for encoding queries and documents.
        vector_store : VectorStore
            Indexed vector database for similarity search.
        # Web search handled directly by web_agent
        ingest_directory : Callable[[Path], object]
            Function to process and index documents from a directory.
        session_db_path : Path
            SQLite database path for conversation persistence.
        quiz_service : QuizService
            Service for generating and evaluating assessments.
        """
        # Core retrieval infrastructure
        self.retriever = Retriever(retrieval_config, embedder=embedder, vector_store=vector_store)
        self.ingest_fn = ingest_directory
        self.mcp_servers = mcp_servers or {}
        self.mcp_server = self.mcp_servers.get("chroma") or next(iter(self.mcp_servers.values()), None)
        
        if self.mcp_servers:
            server_names = ", ".join(self.mcp_servers.keys())
            logger.info("[TutorAgent] MCP servers provided (%s) - agents will use MCP tools with cached lists", server_names)
        
        # Session and state management
        self.sessions: Dict[str, SQLiteSession] = {}  # Learner ID → Active session
        self.session_turn_counts: Dict[str, int] = {}  # Track turns per session for pruning
        self.state = AgentState()  # Shared state for agent communication
        self.session_db_path = session_db_path
        self.max_turns_per_session = 3  # Prune history: create new session after 3 turns
        
        # Quiz and assessment infrastructure
        self.quiz_service = quiz_service
        
        # Temporary context for quiz generation (set during answer() calls)
        self._active_profile: Optional[LearnerProfile] = None
        self._active_extra_context: Optional[str] = None

        # Agent instances (initialized in _build_agents)
        self.ingestion_agent: Agent | None = None
        self.qa_agent: Agent | None = None
        self.note_agent: Agent | None = None
        self.web_agent: Agent | None = None
        self.quiz_agent: Agent | None = None
        self.routing_agent: Agent | None = None
        self._routing_session: SQLiteSession | None = None

        self._build_agents()

    def _build_agents(self) -> None:
        """
        Construct the specialist agents for the agent-first architecture.
        
        Each agent owns a single responsibility:
        - ingestion_agent: handles new document ingestion
        - qa_agent: retrieval-augmented Q&A
        - note_agent: summaries and note files
        - web_agent: current events via web search
        - quiz_agent: quiz generation via QuizService
        - routing_agent: LLM fallback router that emits structured JSON
        """
        logger.debug("[TutorAgent] Building specialist agents with persistent MCP context")
        self.ingestion_agent = build_ingestion_agent(self.ingest_fn)
        self.web_agent = build_web_agent(state=self.state)
        self.qa_agent = build_qa_agent(
            self.retriever, 
            self.state, 
            self.MIN_CONFIDENCE, 
            mcp_servers=list(self.mcp_servers.values()),  # Pass persistent MCP connections (tools cached per session)
            mcp_server_names=list(self.mcp_servers.keys()),  # Pass server names for proper detection
        )
        self.note_agent = build_note_agent(
            self.retriever,
            self.state,
            self.MIN_CONFIDENCE,
            mcp_servers=list(self.mcp_servers.values()),
            mcp_server_names=list(self.mcp_servers.keys()),
        )
        self.quiz_agent = build_quiz_agent(
            self.quiz_service,
            self.state,
            get_profile=lambda: self._active_profile,
            get_extra_context=lambda: self._active_extra_context,
        )
        if self.mcp_servers:
            logger.info("[TutorAgent] Agents built with MCP tool access (%d server(s))", len(self.mcp_servers))
        else:
            logger.info("[TutorAgent] Agents built without MCP servers (direct vector store access)")
        routing_instructions = (
            "You are the routing agent. You must decide which specialist agent should handle a learner request.\n"
            "- Valid routes: qa, note, quiz, web, ingestion.\n"
            "- Respond ONLY with compact JSON: "
            '{"route": "...", "reason": "...", "source_mentions": [], "quiz_topic": null, "quiz_count": null, "confidence": 0-1}.\n'
            "- Prefer deterministic rules: quizzes/tests -> quiz, summaries/notes/files -> note, news/current events -> web, ingestion/upload/indexing -> ingestion, "
            "otherwise default to qa.\n"
            "- Preserve exact document titles or filenames in source_mentions; never use placeholders like 'uploaded documents'.\n"
            "- If unsure, pick the most likely route but lower confidence."
        )
        self.routing_agent = Agent(
            name="routing_agent",
            model="gpt-4o-mini",
            instructions=routing_instructions,
        )
        self._routing_session = SQLiteSession(
            "ai_tutor_router",
            db_path=str(self.session_db_path),
        )


    def evaluate_quiz(
        self,
        *,
        quiz: Quiz,
        answers: List[int],
        profile: Optional[LearnerProfile],
    ) -> QuizEvaluation:
        """Score a learner's quiz submission and return detailed feedback."""
        return self.quiz_service.evaluate_quiz(
            quiz=quiz,
            answers=answers,
            profile=profile,
        )

    def answer(
        self,
        learner_id: str,
        question: str,
        mode: str,
        style_hint: str,
        profile: Optional[LearnerProfile] = None,
        extra_context: Optional[str] = None,
        on_delta: Optional[Callable[[str], None]] = None,
    ) -> TutorResponse:
        """Synchronously orchestrate the multi-agent run and produce a TutorResponse."""
        try:
            # Check if we're already in an event loop
            asyncio.get_running_loop()
            # If we're in a loop, raise an error suggesting to use answer_async instead
            raise RuntimeError(
                "Cannot call answer() from within an async context. "
                "Use answer_async() instead or call from a sync context."
            )
        except RuntimeError as e:
            if "Cannot call answer()" in str(e):
                raise
            # No running loop, safe to use asyncio.run()
        return asyncio.run(
            self._answer_async(
                learner_id=learner_id,
                question=question,
                mode=mode,
                style_hint=style_hint,
                profile=profile,
                extra_context=extra_context,
                on_delta=on_delta,
            )
            )
    
    async def answer_async(
        self,
        learner_id: str,
        question: str,
        mode: str,
        style_hint: str,
        profile: Optional[LearnerProfile] = None,
        extra_context: Optional[str] = None,
        on_delta: Optional[Callable[[str], None]] = None,
    ) -> TutorResponse:
        """Asynchronously orchestrate the multi-agent run and produce a TutorResponse."""
        return await self._answer_async(
            learner_id=learner_id,
            question=question,
            mode=mode,
            style_hint=style_hint,
            profile=profile,
            extra_context=extra_context,
            on_delta=on_delta,
        )

    async def _answer_async(
        self,
        learner_id: str,
        question: str,
        mode: str,
        style_hint: str,
        profile: Optional[LearnerProfile],
        extra_context: Optional[str],
        on_delta: Optional[Callable[[str], None]],
    ) -> TutorResponse:
        import time

        answer_start = time.time()
        logger.info("[TutorAgent] Starting answer generation for learner=%s", learner_id)

        current_turn = self.session_turn_counts.get(learner_id, 0)
        if current_turn > 0 and current_turn % self.max_turns_per_session == 0:
            logger.info(
                "[TutorAgent] Pruning history for %s after %s turns",
                learner_id,
                current_turn,
            )
            if learner_id in self.sessions:
                del self.sessions[learner_id]

        session = self._get_session(learner_id)
        self.state.reset()
        self.session_turn_counts[learner_id] = current_turn + 1

        decision = await self._route_question(
            question=question,
            extra_context=extra_context,
            profile=profile,
        )
        logger.info(
            "[TutorAgent] Routing decision: route=%s reason=%s deterministic=%s source_filter=%s",
            decision.target,
            decision.reason,
            decision.deterministic,
            decision.source_filter,
        )

        if not decision.source_filter and should_use_source_filter(question):
            decision.source_filter = extract_source_mentions(question)

        if decision.target == "quiz":
            decision.quiz_topic = decision.quiz_topic or self._infer_topic_from_request(question)
            decision.quiz_count = decision.quiz_count or self._infer_count_from_request(question)

        prompt = self._build_agent_prompt(
            question=question,
            mode=mode,
            style_hint=style_hint,
            profile=profile,
            extra_context=extra_context,
            decision=decision,
        )

        self._active_profile = profile
        self._active_extra_context = extra_context
        self.state.last_quiz = None
        try:
            answer_text, quiz_payload = await self._execute_decision(
                decision=decision,
                prompt=prompt,
                session=session,
                on_delta=on_delta,
            )
        finally:
            self._active_profile = None
            self._active_extra_context = None

        if quiz_payload is None and self.state.last_quiz is not None:
            quiz_payload = self.state.last_quiz

        if quiz_payload is None and self._should_force_quiz(question):
            quiz_payload = self.quiz_service.generate_quiz(
                topic=self._infer_topic_from_request(question),
                profile=profile,
                num_questions=self._infer_count_from_request(question),
                difficulty=None,
                extra_context=extra_context,
            )
            self.state.last_quiz = quiz_payload
            answer_text = (
                f"I've prepared a {len(quiz_payload.questions)}-question quiz on {quiz_payload.topic} for you. "
                "You can start taking the quiz now!"
            )

        if quiz_payload is None and not self.state.last_citations:
            answer_text = self._strip_citation_markers(answer_text)

        if quiz_payload is None:
            processed, computed_quiz = self._process_quiz_directive(
                answer_text,
                profile=profile,
                extra_context=extra_context,
            )
            if computed_quiz is not None:
                quiz_payload = computed_quiz
                answer_text = processed

        hits = self.state.last_hits if not quiz_payload else []
        citations = self.state.last_citations if not quiz_payload else []

        if decision.target == "quiz":
            source = "quiz"
        elif decision.target == "web":
            source = "web"
        elif decision.target == "note":
            source = "notes"
        elif decision.target == "ingestion":
            source = "ingestion"
        else:
            source = self.state.last_source

        total_answer_duration = time.time() - answer_start
        logger.info("[TutorAgent] Answer generation complete in %.2fs", total_answer_duration)

        return TutorResponse(
            answer=answer_text,
            hits=hits,
            citations=citations,
            style=style_hint,
            source=source,
            quiz=quiz_payload,
        )

    async def _route_question(
        self,
        question: str,
        extra_context: Optional[str],
        profile: Optional[LearnerProfile],
    ) -> RoutingDecision:
        decision = apply_deterministic_routing(question, extra_context)
        if decision:
            return decision
        return await self._route_with_llm(question, extra_context, profile)

    async def _route_with_llm(
        self,
        question: str,
        extra_context: Optional[str],
        profile: Optional[LearnerProfile],
    ) -> RoutingDecision:
        if not self.routing_agent:
            return RoutingDecision(
                target="qa",
                reason="Routing agent unavailable; defaulting to QA",
                deterministic=False,
                confidence=0.0,
            )

        routing_prompt = self._build_routing_prompt(
            question=question,
            extra_context=extra_context,
            profile=profile,
        )
        session = self._get_routing_session()

        try:
            result = await Runner.run(self.routing_agent, input=routing_prompt, session=session)
        except Exception as exc:
            logger.error("[TutorAgent] Routing agent failed: %s", exc, exc_info=True)
            return RoutingDecision(
                target="qa",
                reason="Routing agent failure; default to QA",
                deterministic=False,
                confidence=0.0,
            )

        payload_text = result.final_output.strip() if result and result.final_output else ""
        decision = self._parse_routing_response(payload_text)
        if decision is None:
            logger.warning("[TutorAgent] Failed to parse routing response: %s", payload_text)
            return RoutingDecision(
                target="qa",
                reason="Routing response unreadable; default to QA",
                deterministic=False,
                confidence=0.0,
            )
        decision.deterministic = False
        return decision

    def _build_routing_prompt(
        self,
        question: str,
        extra_context: Optional[str],
        profile: Optional[LearnerProfile],
    ) -> str:
        sections = [
            "Decide the best agent route for the learner request. Remember to output compact JSON.",
            "",
            "Learner request:",
            question,
            "",
        ]
        if profile:
            sections.append("Learner profile summary:")
            sections.append(self._render_profile_summary(profile))
            sections.append("")
        if extra_context:
            sections.append("Session uploads summary:")
            sections.append(extra_context[:1000])
            sections.append("")
        sections.append("Return JSON with keys route, reason, source_mentions, quiz_topic, quiz_count, confidence.")
        return "\n".join(sections)

    def _parse_routing_response(self, text: str) -> Optional[RoutingDecision]:
        if not text:
            return None
        try:
            start = text.index("{")
            end = text.rindex("}") + 1
            payload = json.loads(text[start:end])
        except (ValueError, json.JSONDecodeError):
            logger.debug("[TutorAgent] Unable to parse routing JSON: %s", text)
            return None

        route = str(payload.get("route", "qa")).strip().lower()
        if route not in {"qa", "note", "quiz", "web", "ingestion"}:
            route = "qa"

        reason = str(payload.get("reason") or "LLM routing fallback")
        source_mentions_raw = payload.get("source_mentions") or []
        source_mentions = [
            str(item).strip()
            for item in source_mentions_raw
            if isinstance(item, str) and item.strip()
        ] or None

        quiz_topic = payload.get("quiz_topic")
        if isinstance(quiz_topic, str):
            quiz_topic = quiz_topic.strip()
        else:
            quiz_topic = None
        quiz_count = payload.get("quiz_count")
        try:
            quiz_count_int = int(quiz_count) if quiz_count is not None else None
        except (TypeError, ValueError):
            quiz_count_int = None

        confidence = payload.get("confidence")
        try:
            confidence_value = float(confidence)
        except (TypeError, ValueError):
            confidence_value = 0.5

        return RoutingDecision(
            target=route,  # type: ignore[arg-type]
            reason=reason,
            source_filter=source_mentions,
            quiz_topic=quiz_topic or None,
            quiz_count=quiz_count_int,
            deterministic=False,
            confidence=confidence_value,
        )

    def _build_agent_prompt(
        self,
        *,
        question: str,
        mode: str,
        style_hint: str,
        profile: Optional[LearnerProfile],
        extra_context: Optional[str],
        decision: RoutingDecision,
    ) -> str:
        sections: List[str] = [
            f"Learner mode: {mode}",
            f"Preferred explanation style: {style_hint}",
            f"Routing reason: {decision.reason}",
            "",
        ]
        if profile:
            sections.append("Learner profile summary:")
            sections.append(self._render_profile_summary(profile))
            sections.append("")
        if extra_context and decision.target != "quiz":
            sections.append("Session-provided context (verbatim, do not leak sensitive info):")
            sections.append(extra_context[:2000])
            sections.append("")
        if decision.source_filter:
            sections.append(
                "Source filter hints (pass via `source_filter` when calling retrieve_local_context): "
                + ", ".join(decision.source_filter)
            )
            sections.append("")
        if decision.target == "quiz":
            sections.append("Quiz metadata:")
            sections.append(f"topic: {decision.quiz_topic or 'general review'}")
            sections.append(f"count: {decision.quiz_count or 4}")
            sections.append("")
            sections.append("Use generate_quiz exactly once.")
        sections.append("Learner request:")
        sections.append(question)
        return "\n".join(sections)

    async def _execute_decision(
        self,
        *,
        decision: RoutingDecision,
        prompt: str,
        session: SQLiteSession,
        on_delta: Optional[Callable[[str], None]],
    ) -> tuple[str, Optional[Quiz]]:
        if decision.target == "quiz":
            answer = await self._run_quiz_agent(prompt, session, on_delta)
            return answer, self.state.last_quiz

        if decision.target == "web":
            answer = await self._run_web_agent(prompt, session, on_delta)
            self.state.last_source = "web"
            return answer, None

        if decision.target == "ingestion":
            answer = await self._run_domain_agent(self.ingestion_agent, prompt, session, on_delta)
            return answer, None

        if decision.target == "note":
            answer = await self._run_domain_agent(self.note_agent, prompt, session, on_delta)
            if self.state.last_source is None:
                self.state.last_source = "notes"
            return answer, None

        answer = await self._run_domain_agent(
            self.qa_agent,
            prompt,
            session,
            on_delta,
            allow_web_fallback=True,
        )
        return answer, None

    async def _run_domain_agent(
        self,
        agent: Agent | None,
        prompt: str,
        session: SQLiteSession,
        on_delta: Optional[Callable[[str], None]],
        *,
        allow_web_fallback: bool = False,
    ) -> str:
        if agent is None:
            return "I could not complete that request because the required agent is unavailable."
        try:
            result = await Runner.run(agent, input=prompt, session=session)
        except Exception as exc:
            logger.error("[TutorAgent] Agent %s failed: %s", agent.name, exc, exc_info=True)
            return f"I encountered an error while delegating to {agent.name}: {exc}"

        text = result.final_output.strip() if result and result.final_output else ""
        if allow_web_fallback and self._should_web_fallback(text):
            logger.info("[TutorAgent] QA requested web fallback")
            return await self._run_web_agent(prompt, session, on_delta)

        if on_delta and text:
            for char in text:
                on_delta(char)

        if text:
            return text
        return "I could not generate a response. Please try rephrasing your request."

    async def _run_web_agent(
        self,
        prompt: str,
        session: SQLiteSession,
        on_delta: Optional[Callable[[str], None]],
    ) -> str:
        if self.web_agent is None:
            return "Web search is unavailable at the moment."
        try:
            result = await Runner.run(self.web_agent, input=prompt, session=session)
        except Exception as exc:
            logger.error("[TutorAgent] Web agent failed: %s", exc, exc_info=True)
            return f"I attempted to search the web but encountered an error: {exc}"

        text = result.final_output.strip() if result and result.final_output else ""
        if on_delta and text:
            for char in text:
                on_delta(char)
        return text or "I could not find relevant current information."

    async def _run_quiz_agent(
        self,
        prompt: str,
        session: SQLiteSession,
        on_delta: Optional[Callable[[str], None]],
    ) -> str:
        if self.quiz_agent is None:
            return "Quiz generation is currently unavailable."
        try:
            result = await Runner.run(self.quiz_agent, input=prompt, session=session)
        except Exception as exc:
            logger.error("[TutorAgent] Quiz agent failed: %s", exc, exc_info=True)
            return f"Quiz generation failed: {exc}"

        text = result.final_output.strip() if result and result.final_output else ""
        if on_delta and text:
            for char in text:
                on_delta(char)
        return text or "Prepared the requested quiz."

    def _should_web_fallback(self, answer: str) -> bool:
        normalized = answer.strip().lower()
        return normalized.startswith("handoff to web_agent") or normalized.startswith("handoff to web agent")

    def _get_routing_session(self) -> SQLiteSession:
        if self._routing_session is None:
            self._routing_session = SQLiteSession(
                "ai_tutor_router",
                db_path=str(self.session_db_path),
            )
        return self._routing_session

    def _get_session(self, learner_id: str) -> SQLiteSession:
        """
        Get or create a conversation session with automatic daily rotation and history pruning.
        
        This method implements token overflow prevention through:
        1. Date-based session keys (daily rotation)
        2. Turn-based pruning (new session after max_turns_per_session turns)
        
        This prevents prompt length from growing unbounded while maintaining recent context
        for anti-loop detection and conversation coherence.
        
        Session Key Format
        ------------------
        ai_tutor_{learner_id}_{YYYYMMDD}_{turn_batch}
        
        Example: "ai_tutor_student123_20251023_0" (first 3 turns)
                 "ai_tutor_student123_20251023_1" (next 3 turns)
        
        Parameters
        ----------
        learner_id : str
            Unique identifier for the learner (used for profile lookup and session key).
        
        Returns
        -------
        SQLiteSession
            Active session object for this learner. History is pruned to last 3 turns
            to prevent prompt poisoning and reduce synthesis time.
        
        Notes
        -----
        - Sessions are cached in memory for performance
        - Automatic rotation occurs at midnight (based on server timezone)
        - History pruning: new session created after max_turns_per_session turns
        - Previous sessions remain in SQLite but are not loaded into context
        - Manual clearing available via clear_session() or clear_sessions.py script
        """
        # Use date-based session IDs to auto-rotate daily (prevents token accumulation)
        today = datetime.now().strftime("%Y%m%d")
        
        # Check current turn count for this learner
        turn_count = self.session_turn_counts.get(learner_id, 0)
        turn_batch = turn_count // self.max_turns_per_session
        
        # Create session key with turn batch to enable pruning
        session_key = f"ai_tutor_{learner_id}_{today}_{turn_batch}"
        
        # Check if we have a cached session for this learner
        session = self.sessions.get(learner_id)
        
        # Create new session if:
        # 1. None exists
        # 2. Session key changed (new day or new turn batch)
        if (session is None or 
            getattr(session, '_session_key', None) != session_key):
            
            session = SQLiteSession(
                session_key,
                db_path=str(self.session_db_path),
            )
            # Store session key for comparison on next access
            session._session_key = session_key  # type: ignore
            self.sessions[learner_id] = session
            logger.debug(f"Created new session for {learner_id}: {session_key} (turn batch {turn_batch})")
        
        return session
    
    def clear_session(self, learner_id: str) -> None:
        """
        Clear the in-memory conversation session for a learner.
        
        This removes the cached session from memory, forcing creation of a fresh
        session on the next interaction. The SQLite database retains historical
        records, but they won't be loaded into the agent's context.
        
        Parameters
        ----------
        learner_id : str
            Unique identifier for the learner whose session should be cleared.
        
        Notes
        -----
        - Only removes from memory cache, not from SQLite database
        - To permanently delete from database, use scripts/clear_sessions.py
        - Next interaction will create a fresh session with no conversation history
        """
        if learner_id in self.sessions:
            del self.sessions[learner_id]
        if learner_id in self.session_turn_counts:
            del self.session_turn_counts[learner_id]
        # Note: This doesn't delete from SQLite, just removes from memory
        # The session will start fresh on next question

    @staticmethod
    def _strip_citation_markers(answer: str) -> str:
        cleaned = re.sub(r"\[\s*\d+(?:\s*,\s*\d+)*\s*\]", "", answer)
        return re.sub(r"\s{2,}", " ", cleaned).strip()

    @staticmethod
    def _render_profile_summary(profile: LearnerProfile) -> str:
        lines = [
            f"Name: {profile.name or profile.learner_id}",
            f"Total study time (minutes): {profile.total_time_minutes:.1f}",
        ]
        if profile.domain_strengths:
            strengths = sorted(profile.domain_strengths.items(), key=lambda item: item[1], reverse=True)[:3]
            strength_lines = ", ".join(f"{domain}: {score:.2f}" for domain, score in strengths)
            lines.append(f"Domain strengths: {strength_lines}")
        if profile.difficulty_preferences:
            prefs = ", ".join(f"{domain}: {pref}" for domain, pref in list(profile.difficulty_preferences.items())[:3])
            lines.append(f"Difficulty preferences: {prefs}")
        if profile.next_topics:
            next_topics = ", ".join(f"{domain}: {topic}" for domain, topic in list(profile.next_topics.items())[:3])
            lines.append(f"Upcoming topics: {next_topics}")
        return "\n".join(lines)

    def _process_quiz_directive(
        self,
        answer_text: str,
        profile: Optional[LearnerProfile],
        extra_context: Optional[str],
    ) -> tuple[str, Optional[Quiz]]:
        text = answer_text.strip()
        if not text.startswith("{"):
            return answer_text, None
        try:
            payload = json.loads(text)
        except json.JSONDecodeError:
            return answer_text, None
        if not isinstance(payload, dict):
            return answer_text, None
        if payload.get("action") != "generate_quiz":
            return answer_text, None

        topic_raw = payload.get("topic") or payload.get("subject") or "general review"
        topic = str(topic_raw).strip() or "general review"
        count_raw = payload.get("count") or payload.get("num_questions") or 4
        try:
            count = int(count_raw)
        except (TypeError, ValueError):
            count = 4
        count = max(3, min(count, 40))  # Allow up to 40 questions
        message = str(payload.get("message") or "").strip()

        quiz = self.quiz_service.generate_quiz(
            topic=topic,
            profile=profile,
            num_questions=count,
            difficulty=None,
            extra_context=extra_context,
        )
        if not message:
            message = f"I've prepared a {count}-question quiz on {quiz.topic}. Scroll down to take it."
        return message, quiz

    @staticmethod
    def _should_force_quiz(question: str) -> bool:
        lowered = question.lower()
        keywords = [
            "quiz",
            "quizzes",
            "practice questions",
            "practice quiz",
            "give me questions",
            "mcq",
            "multiple choice",
            "test me",
        ]
        return any(keyword in lowered for keyword in keywords)

    @staticmethod
    def _infer_topic_from_request(question: str) -> str:
        # Check if requesting quiz from documents
        if re.search(r"from\s+(?:the\s+)?documents?|based\s+on\s+documents?|using\s+(?:the\s+)?(?:uploaded\s+)?(?:documents?|files?)", question, flags=re.IGNORECASE):
            return "uploaded documents"
        
        match = re.search(r"(?:about|on|regarding)\s+(.+)", question, flags=re.IGNORECASE)
        topic = match.group(1).strip() if match else question.strip()
        topic = re.sub(r"[\.\?!]+$", "", topic)
        # Clean up quiz-related words from topic
        topic = re.sub(r"\b(?:quiz|quizzes|questions?|test)\b", "", topic, flags=re.IGNORECASE).strip()
        return topic or "general review"

    @staticmethod
    def _infer_count_from_request(question: str) -> int:
        match = re.search(r"(\d+)\s*(?:question|questions|quiz|quizzes|mcq)", question, flags=re.IGNORECASE)
        if not match:
            match = re.search(r"(\d+)", question)
        if match:
            try:
                value = int(match.group(1))
                return max(3, min(value, 40))  # Maximum number of questions is 40
            except ValueError:
                pass
        return 4

