project_name: "Personal STEM Instructor"

# LLM Configuration
model:
  name: "gpt-4o-mini"                  # Model for agent orchestration and quiz generation
  provider: "openai"                    # OpenAI API
  temperature: 0.15                     # Low temperature for consistent, focused responses
  max_output_tokens: 2048               # Default max tokens (overridden for large quizzes)
  mode: "chat"                          # Chat mode for conversational context

# Embedding Model Configuration
embeddings:
  model: "BAAI/bge-base-en"            # Sentence transformer for vector embeddings
  provider: "sentence-transformers"     # Local embeddings (no API calls)
  batch_size: 256                       # Batch size for embedding generation
  normalize: true                       # Normalize embeddings for cosine similarity
  dimension: null                       # Auto-detect embedding dimension

# Document Chunking Configuration
chunking:
  chunk_size: 500                       # Tokens per chunk (balance between context and precision)
  chunk_overlap: 80                     # Overlap between chunks (helps with context continuity)
  tokenizer: null                       # Auto-detect tokenizer

# Retrieval Configuration
retrieval:
  top_k: 5                              # Default number of results per query
                                        # Note: Auto-increased to 50 for uploaded document queries
                                        # with source filtering enabled

paths:
  raw_data_dir: "data/raw"
  processed_data_dir: "data/processed"
  vector_store_dir: "data/vector_store"
  chunks_index: "data/processed/chunks.jsonl"
  logs_dir: "logs"
  profiles_dir: "data/processed/profiles"

logging:
  level: DEBUG  # See agent handoffs, tool calls, profile updates
  use_json: false

course_defaults:
  weeks: 12
  lessons_per_week: 3
  domains:
    - "math"
    - "physics"
    - "cs"
