project_name: "Personal STEM Instructor"

model:
  name: "gpt-4o-mini"
  provider: "openai"
  temperature: 0.15
  max_output_tokens: 2048
  mode: "chat"

embeddings:
  model: "BAAI/bge-base-en"
  provider: "sentence-transformers"
  batch_size: 256
  normalize: true
  dimension: null

chunking:
  chunk_size: 500
  chunk_overlap: 80
  tokenizer: null

retrieval:
  top_k: 5

paths:
  raw_data_dir: "data/raw"
  processed_data_dir: "data/processed"
  vector_store_dir: "data/vector_store"
  chunks_index: "data/processed/chunks.jsonl"
  logs_dir: "logs"
  profiles_dir: "data/processed/profiles"

logging:
  level: DEBUG  # See agent handoffs, tool calls, profile updates
  use_json: false

course_defaults:
  weeks: 12
  lessons_per_week: 3
  domains:
    - "math"
    - "physics"
    - "cs"
