project_name: "Personal STEM Instructor"

model:
  name: "gemini-1.5-pro"
  provider: "litellm"
  temperature: 0.15
  max_output_tokens: 2048
  mode: "chat"

embeddings:
  model: "gemini-embedding-001"
  provider: "google-genai"
  batch_size: 32
  normalize: true
  dimension: 768

chunking:
  chunk_size: 900
  chunk_overlap: 120
  tokenizer: null

retrieval:
  top_k: 8

paths:
  raw_data_dir: "data/raw"
  processed_data_dir: "data/processed"
  vector_store_dir: "data/vector_store"
  chunks_index: "data/processed/chunks.jsonl"
  logs_dir: "logs"

logging:
  level: "INFO"
  json: false
